name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      
      - name: Tests integration
#        env:
#          HOST: ${{ secrets.HOST }}
#          PORT: ${{ secrets.PORT }}
#          SHAREDIR: ${{ secrets.SHAREDIR }}
#          TYPE: ${{ secrets.TYPE }}
        run: go test -v -tags=integration ./...

      - name: Tests unit
        run: go test -v -tags=unit ./...